// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace App1
{
    [default_interface]
    runtimeclass BlankPage : Microsoft.UI.Xaml.Controls.Page
    {
        BlankPage();
        Int32 MyProperty;
    }
}
